// The starter config applied browser globals and the React plugins to EVERY
// .ts/.tsx file, including the Node server under api/, the Drizzle schema, and
// the operator scripts. That is why lint had never been part of CI: it reported
// dozens of React-only findings against server code. This config matches the
// three kinds of code actually in the repository.
import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

// An underscore prefix is the project's existing convention for a binding that
// is intentionally unused (destructuring a field only to drop it, for example).
const unusedVars = [
  'error',
  { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
]

export default defineConfig([
  globalIgnores([
    'dist',
    'build',
    'coverage',
    'db/demo-schema',
    'playwright-report',
    'test-results',
    // Vendored shadcn/ui primitives. These are generated by the shadcn CLI and
    // are replaced wholesale when it is re-run, so local edits made to satisfy
    // lint would be silently lost on the next update.
    'src/components/ui/**',
  ]),

  // ── Server, schema and tooling: Node, no React ────────────────────────────
  {
    files: ['api/**/*.ts', 'db/**/*.ts', 'contracts/**/*.ts', 'scripts/**/*.ts', 'tests/**/*.ts'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: { ecmaVersion: 2022, globals: globals.node },
    rules: { '@typescript-eslint/no-unused-vars': unusedVars },
  },

  // Operator probes and one-off maintenance scripts. These talk to live
  // hardware and to untyped JSON over HTTP, and they are excluded from the
  // TypeScript build (tsconfig.server.json covers api, contracts and db only),
  // so `any` here is a deliberate boundary rather than a lapse.
  {
    files: ['scripts/**/*.ts'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },

  // ── Frontend ──────────────────────────────────────────────────────────────
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: { ecmaVersion: 2020, globals: globals.browser },
    rules: { '@typescript-eslint/no-unused-vars': unusedVars },
  },

  // Context and provider modules deliberately export their hook next to the
  // provider component, which is the documented pattern for both tRPC and a
  // React context. Fast Refresh grouping is not a reason to split them.
  {
    files: ['src/providers/**/*.tsx', 'src/i18n/index.tsx', 'src/components/shared.tsx'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },

  // Playwright specs run in Node and drive a browser; both global sets apply.
  {
    files: ['tests/e2e/**/*.ts'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
])
