// Merges researched brand maps (/mnt/agents/work/brand-maps/*.json) into the
// built-in library (db/device-profile-library.ts) and REGENERATES that file.
// Re-runnable: agent maps with registers override the curated base; empty
// agent maps only append notes. Run: npx tsx scripts/merge-brand-maps.ts
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { DEVICE_PROFILE_LIBRARY, type DeviceProfileEntry } from "../db/device-profile-library";
import type { RegisterDef } from "@contracts/modbus";

const DIR = "/mnt/agents/work/brand-maps";

interface AgentMap {
  brand: string;
  model: string;
  deviceType: "inverter" | "bess";
  protocol: "rtu" | "tcp";
  source: "vendor" | "community" | "template";
  sourceUrl?: string;
  notes?: string;
  registerMap: RegisterDef[];
  faultCodes?: Array<{ code: number; text: string }>;
}

const brandSlug = (b: string) => b.toLowerCase().replace(/[^a-z].*$/, "").trim();

const merged: DeviceProfileEntry[] = DEVICE_PROFILE_LIBRARY.map((e) => ({ ...e }));
const byBrand = new Map(merged.map((e) => [brandSlug(e.brand), e]));

if (existsSync(DIR)) {
  for (const file of readdirSync(DIR).filter((f) => f.endsWith(".json"))) {
    const agent = JSON.parse(readFileSync(`${DIR}/${file}`, "utf8")) as AgentMap;
    const base = byBrand.get(brandSlug(agent.brand));
    if (!base) {
      console.log(`  + new brand from research: ${agent.brand}`);
      merged.push({
        model: `${brandSlug(agent.brand)}-${file.replace(".json", "")}`,
        label: agent.model,
        brand: agent.brand,
        deviceType: agent.deviceType,
        protocol: agent.protocol,
        source: agent.source,
        sourceUrl: agent.sourceUrl,
        notes: agent.notes,
        registerMap: agent.registerMap,
        faultCodes: agent.faultCodes,
      });
      continue;
    }
    if (agent.registerMap.length > 0) {
      // Normalize: keys ending in Kw must carry kW unit after 0.001 scaling
      for (const r of agent.registerMap) {
        if (r.key.endsWith("Kw") && r.unit === "W" && r.scale === 0.001) r.unit = "kW";
        if (!r.wordSwap) delete r.wordSwap;
      }
      base.registerMap = agent.registerMap;
      base.source = agent.source;
      base.sourceUrl = agent.sourceUrl ?? base.sourceUrl;
      base.protocol = agent.protocol;
      if (agent.notes) base.notes = agent.notes;
      if (agent.faultCodes?.length) base.faultCodes = agent.faultCodes;
      console.log(`  ✓ ${base.brand}: replaced with researched map (${agent.registerMap.length} regs, ${agent.source})`);
    } else {
      if (agent.notes) base.notes = `${base.notes ?? ""} Research: ${agent.notes}`.trim();
      if (agent.sourceUrl) base.sourceUrl = agent.sourceUrl;
      console.log(`  · ${base.brand}: kept base template (research found no public map), notes merged`);
    }
  }
} else {
  console.log("no research dir — regenerating from base only");
}

const header = `// Built-in device profile library — ${merged.filter((e) => e.deviceType === "inverter").length} inverter brands + BESS profiles.
// GENERATED by scripts/merge-brand-maps.ts — do not hand-edit; edit the curated
// base (git history) or the research JSONs and re-run the merge.
// source: "vendor" = official doc, "community" = open integrations, "template" = verify before field use.
// Addresses are 0-based PDU unless the entry notes say otherwise (SMA native!).
import type { RegisterDef } from "@contracts/modbus";

export interface DeviceProfileEntry {
  model: string;
  label: string;
  brand: string;
  deviceType: "inverter" | "bess" | "weather";
  protocol: "rtu" | "tcp";
  source: "vendor" | "community" | "template";
  sourceUrl?: string;
  notes?: string;
  registerMap: RegisterDef[];
  faultCodes?: Array<{ code: number; text: string }>;
}

`;

const body = `export const DEVICE_PROFILE_LIBRARY: DeviceProfileEntry[] = ${JSON.stringify(merged, null, 2)};\n`;
writeFileSync("db/device-profile-library.ts", header + body);
console.log(`library regenerated: ${merged.length} profiles`);
